title: Gaze Estimation and Prediction in the Wild
email: n.horanyi@pgr.bham.ac.uk
description: Website for the Workshop on Gaze Estimation and Prediction in the Wild at ICCV 2019
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
