title: Gaze Estimation and Prediction in the Wild (GAZE 2019)
email: n.horanyi@pgr.bham.ac.uk
description: Gaze Estimation and Prediction in the Wild Workshop at ICCV 2019
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: UA-99765598-4

